name: '1Password'
description: 'Read items from a 1Password vault'
author: 'Brandon Evans'
inputs:
  device-id:
    require: true
    description: 'A base 32-encoded device ID.'
  sign-in-address:
    required: true
    description: '1Password sign-in address'
  email-address:
    required: true
    description: '1Password username'
  secret-key:
    required: true
    description: '1Password secret key'
  master-password:
    required: true
    description: '1Password master password'
  vault-name:
    required: true
    description: 'The name of the vault containing the desired item.'
  item-name:
    required: true
    description: 'The name of the desired item.'
runs:
  using: 'node12'
  main: 'dist/index.js'
